import { MetadataRoute } from "next";

const BASE_URL = "https://wholesailhub.com";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    // ── Core Marketing Pages ─────────────────────────────────────────────────
    {
      url: BASE_URL,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: `${BASE_URL}/blog`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/about`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/ai-ified`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    // ── Tier 1 Industry Landing Pages ────────────────────────────────────────
    {
      url: `${BASE_URL}/food-beverage`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.95,
    },
    {
      url: `${BASE_URL}/wine-spirits`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.95,
    },
    {
      url: `${BASE_URL}/industrial-supply`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/coffee-tea`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/seafood-meat`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/bakery-distribution`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/floral-nursery`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/produce-dairy`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/specialty-food`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/beauty-cosmetics`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/pet-supply`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    // ── Tier 2 Industry Landing Pages ────────────────────────────────────────
    {
      url: `${BASE_URL}/jan-san`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/building-materials`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/agricultural-supply`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/apparel-fashion`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/auto-parts`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/chemical-supply`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    // ── Tier 3 Industry Landing Pages ────────────────────────────────────────
    {
      url: `${BASE_URL}/supplements`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/electrical-supply`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/tobacco-vape`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/restaurant-equipment`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/packaging-supply`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/plumbing-hvac`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/office-breakroom`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/craft-art-supply`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/jewelry-accessories`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    // ── New Industry Landing Pages (March 2026) ───────────────────────────────
    {
      url: `${BASE_URL}/frozen-food`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/candy-confectionery`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/organic-natural`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/hardware-tools`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/gift-novelty`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/vending-supply`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/school-supply`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/frozen-dessert`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    // ── Geographic Landing Pages ──────────────────────────────────────────────
    {
      url: `${BASE_URL}/california`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/texas`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/new-york`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/florida`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/illinois`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/ohio`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/georgia`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    // ── Feature Landing Pages ─────────────────────────────────────────────────
    {
      url: `${BASE_URL}/features/standing-orders`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/features/pricing-tiers`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/features/sms-ordering`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/features/net-terms-billing`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/features/client-health-scoring`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    // ── Blog Posts ────────────────────────────────────────────────────────────
    {
      url: `${BASE_URL}/blog/why-distribution-companies-are-replacing-spreadsheets-with-ordering-portals`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesale-ordering-software-complete-guide`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/how-to-set-up-net-30-billing-for-wholesale-clients`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/shopify-b2b-vs-custom-wholesale-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/food-beverage-distribution-wholesale-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wine-spirits-distributor-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-netsuite-for-distributors`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/replace-quickbooks-spreadsheets-with-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/hubspot-salesforce-distribution-alternatives`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/industrial-supply-distribution-online-ordering`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/produce-distribution-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/craft-beverage-beer-distributor-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/how-to-onboard-wholesale-clients-to-an-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/how-to-set-wholesale-pricing-tiers`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/handshake-faire-vs-custom-wholesale-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    // Vertical-specific blog posts
    {
      url: `${BASE_URL}/blog/coffee-tea-distributor-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/seafood-meat-distributor-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/bakery-distribution-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/floral-nursery-distributor-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/produce-dairy-distributor-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/specialty-food-distributor-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/beauty-cosmetics-distributor-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/pet-supply-distributor-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/jan-san-distributor-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/building-materials-distributor-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/agricultural-supply-distributor-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/apparel-fashion-distributor-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/auto-parts-distributor-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/chemical-supply-distributor-ordering-portal`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    // Competitor comparison posts
    {
      url: `${BASE_URL}/blog/wholesail-vs-faire-for-distributors`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-freshline-for-distributors`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-nuorder-for-distributors`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-repspark-for-distributors`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-integrasoft-acctivate-for-distributors`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-orderease-for-distributors`,
      lastModified: new Date("2026-03-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-bluecart-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-sprwt-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-brandboom-for-apparel-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-cin7-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-tradegecko-quickbooks-commerce-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-woocommerce-b2b-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-ordoro-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-ordermark-for-food-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-choco-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-erp-for-small-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-provi-for-beverage-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-sevenfifty-for-wine-spirits-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-sana-commerce-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-bigcommerce-b2b-edition-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-sellercloud-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-sps-commerce-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-zoho-inventory-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-unleashed-software-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-orderbot-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesail-vs-magento-adobe-commerce-b2b-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    // Niche vertical posts (March 2026)
    {
      url: `${BASE_URL}/blog/craft-spirits-distillery-distributor-portal`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/charcuterie-artisan-cheese-distributor-portal`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/import-distribution-ordering-portal`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/health-wellness-product-distributor-portal`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/baby-children-product-wholesale-distributor-portal`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/outdoor-sporting-goods-distributor-portal`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/latin-hispanic-food-distributor-portal`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/asian-food-distributor-ordering-portal`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/marine-boat-supply-distributor-portal`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/floral-wholesale-distributor-portal`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    // Operational how-to posts (March 2026)
    {
      url: `${BASE_URL}/blog/how-to-write-a-price-increase-letter-to-wholesale-accounts`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/how-to-expand-wholesale-accounts-from-20-to-100`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/how-to-handle-wholesale-returns-and-credits`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/cash-flow-management-for-distribution-companies`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/how-to-reduce-order-errors-in-distribution`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/wholesale-credit-management-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/how-to-set-minimum-order-quantities-wholesale`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/how-to-manage-seasonal-demand-spikes-in-distribution`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/how-to-measure-wholesale-distributor-performance`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/multi-location-wholesale-account-management`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    // Strategic / finance posts (March 2026)
    {
      url: `${BASE_URL}/blog/wholesale-distribution-trends-2026`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/why-wholesale-distributors-lose-accounts`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/how-to-build-a-wholesale-referral-program`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/wholesale-distribution-technology-stack-2026`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/how-to-value-a-distribution-business-for-sale`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/gross-margin-optimization-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/how-ai-is-changing-wholesale-distribution`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/distributor-sales-rep-performance-management`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/wholesale-glossary-distribution-terms`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    // ICP and how-to posts
    {
      url: `${BASE_URL}/blog/wholesale-portal-for-small-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/how-to-stop-losing-orders-to-voicemail`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/how-to-automate-wholesale-invoicing`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/wholesale-client-onboarding-checklist`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/b2b-ecommerce-vs-edi-for-distributors`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/how-sales-reps-use-wholesale-portals`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/net-30-net-60-wholesale-best-practices`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/best-wholesale-software-for-food-distributors-2026`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/how-to-migrate-from-phone-ordering-to-online`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/wholesale-ordering-portal-roi-how-to-calculate`,
      lastModified: new Date("2026-03-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    // Feature and educational posts
    {
      url: `${BASE_URL}/blog/standing-orders-automation-for-wholesale-distributors`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/per-account-pricing-tiers-wholesale-distribution`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/lapsed-client-reengagement-wholesale-distribution`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/sms-ordering-for-wholesale-distributors`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/wholesale-loyalty-program-for-distributors`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/wholesale-distributor-client-health-scoring`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/wholesale-distributor-software-buyers-guide-2026`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog/how-product-drops-build-urgency-in-wholesale`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/b2b-wholesale-portal-vs-marketplace-complete-guide`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/how-to-write-a-wholesale-agreement-for-new-clients`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    // Additional industry vertical posts
    {
      url: `${BASE_URL}/blog/frozen-food-distributor-ordering-portal`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/candy-confectionery-wholesale-ordering-portal`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/organic-natural-food-distributor-portal`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/medical-dental-supply-distributor-portal`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/hardware-tools-distributor-ordering-portal`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/gift-novelty-wholesale-ordering-portal`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/nutrition-supplement-distributor-ordering-portal`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/janitorial-sanitation-distributor-portal`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/vending-supply-distributor-ordering-portal`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog/school-education-supply-distributor-portal`,
      lastModified: new Date("2026-03-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
  ];
}
