export interface Product {
  id: string
  name: string
  price: number
  unit: string
  description: string
  category: string
  minimumOrder?: string
  packaging?: string
  available?: boolean
  coldChainRequired?: boolean
  marketRate?: boolean
  prepayRequired?: boolean
  image?: string | null
  slug?: string
}

export const productCategories = [
  'Fresh Truffles',
  'Caviar',
  'Truffle Butters',
  'Truffle Oils',
  'Salumi',
  'Pre-Sliced Salumi',
  'Seasonings',
  'Preserved Products',
  'Accessories',
] as const

export const products: Product[] = [
  // Fresh Truffles
  {
    id: 'summer-black-truffle',
    name: 'Summer Black Truffles',
    price: 250,
    unit: 'per lb',
    description: 'Tuber Aestivum - Mild aroma, large size. Peak season June. Origin: Abruzzo, Italy',
    category: 'Fresh Truffles',
    minimumOrder: '4 oz minimum',
    available: true,
  },
  {
    id: 'autumn-black-truffle',
    name: 'Autumn Black Truffles (Burgundy)',
    price: 100,
    unit: 'per oz',
    description: 'Tuber Uncinatum - Powerfully pungent, nutty flavors. Origin: Abruzzo, Italy',
    category: 'Fresh Truffles',
    minimumOrder: '5 oz minimum',
    available: true,
  },
  {
    id: 'white-abruzzese-truffle',
    name: 'White Abruzzese Truffle',
    price: 200,
    unit: 'per oz',
    description: 'Tuber Magnatum Pico - Creamy, garlicky with sweet aromatics. Most coveted globally',
    category: 'Fresh Truffles',
    minimumOrder: '8 oz minimum',
    available: true,
  },
  {
    id: 'winter-black-truffle',
    name: 'Winter Black Truffles (Perigords)',
    price: 65,
    unit: 'per oz',
    description: 'Tuber Melanosporum - Intense, chocolatey, earthy. Includes certificate of authenticity',
    category: 'Fresh Truffles',
    minimumOrder: '4 oz minimum',
    available: true,
  },

  // Caviar
  {
    id: 'kaluga-hybrid-1oz',
    name: 'Kaluga Hybrid Caviar 1oz',
    price: 40,
    unit: 'per tin',
    description: 'Buttery, creamy, subtle ocean salt. Large glossy gray pearls with gold highlights',
    category: 'Caviar',
    packaging: '30g (1oz) tin',
    available: true,
  },
  {
    id: 'kaluga-hybrid-2oz',
    name: 'Kaluga Hybrid Caviar 2oz',
    price: 80,
    unit: 'per jar',
    description: 'Buttery, creamy, subtle ocean salt. Large glossy gray pearls with gold highlights',
    category: 'Caviar',
    packaging: '60g (2oz) glass jar',
    available: true,
  },
  {
    id: 'kaluga-hybrid-125g',
    name: 'Kaluga Hybrid Caviar 125g',
    price: 155,
    unit: 'per container',
    description: 'Buttery, creamy, subtle ocean salt. Large glossy gray pearls with gold highlights',
    category: 'Caviar',
    packaging: '125g glass container/tin',
    available: true,
  },
  {
    id: 'russian-osetra-1oz',
    name: 'Russian Osetra Caviar 1oz',
    price: 45,
    unit: 'per tin',
    description: 'Nutty and buttery flavor. Deep amber colored pearls. Privately farmed from Russia',
    category: 'Caviar',
    packaging: '30g (1oz) tin',
    available: true,
  },
  {
    id: 'russian-osetra-2oz',
    name: 'Russian Osetra Caviar 2oz',
    price: 85,
    unit: 'per jar',
    description: 'Nutty and buttery flavor. Deep amber colored pearls. Privately farmed from Russia',
    category: 'Caviar',
    packaging: '60g (2oz) glass jar',
    available: true,
  },
  {
    id: 'siberian-caviar-1oz',
    name: 'Siberian Caviar 1oz',
    price: 60,
    unit: 'per tin',
    description: 'Light-to-dark-gray pearls, tender consistency. Malossol grade with minimal salt',
    category: 'Caviar',
    packaging: '30g (1oz) tin',
    available: true,
  },
  {
    id: 'siberian-caviar-2oz',
    name: 'Siberian Caviar 2oz',
    price: 100,
    unit: 'per jar',
    description: 'Light-to-dark-gray pearls, tender consistency. Malossol grade with minimal salt',
    category: 'Caviar',
    packaging: '60g (2oz) glass jar',
    available: true,
  },
  {
    id: 'russian-sturgeon-1oz',
    name: 'Russian Sturgeon Caviar 1oz',
    price: 75,
    unit: 'per tin',
    description: 'Imperial grade. Light-brown to caramel eggs. Saline-infused richness',
    category: 'Caviar',
    packaging: '30g (1oz) tin',
    available: true,
  },
  {
    id: 'beluga-hybrid-1oz',
    name: 'Beluga Hybrid Caviar 1oz',
    price: 200,
    unit: 'per tin',
    description: 'Tender, delicate, buttery. Most expensive type due to scarcity. From Bulgaria',
    category: 'Caviar',
    packaging: '30g (1oz) tin',
    available: true,
  },
  {
    id: 'beluga-hybrid-2oz',
    name: 'Beluga Hybrid Caviar 2oz',
    price: 380,
    unit: 'per jar',
    description: 'Tender, delicate, buttery. Most expensive type due to scarcity. From Bulgaria',
    category: 'Caviar',
    packaging: '60g (2oz) glass jar',
    available: true,
  },

  // Truffle Butters
  {
    id: 'black-truffle-butter-8oz',
    name: 'Black Truffle Butter 8oz',
    price: 10.63,
    unit: 'per ea',
    description: 'Maison Crayssac premium truffle butter',
    category: 'Truffle Butters',
    packaging: 'Sold by case only',
    available: true,
  },
  {
    id: 'white-truffle-butter-8oz',
    name: 'White Truffle Butter 8oz',
    price: 10.63,
    unit: 'per ea',
    description: 'Maison Crayssac premium truffle butter',
    category: 'Truffle Butters',
    packaging: 'Sold by case only',
    available: true,
  },

  // Truffle Oils
  {
    id: 'black-truffle-oil-100ml',
    name: 'Black Truffle Olive Oil 100ml',
    price: 6.13,
    unit: 'per bottle',
    description: 'Premium black truffle infused olive oil',
    category: 'Truffle Oils',
    packaging: '100ml bottle, sold by case',
    available: true,
  },
  {
    id: 'white-truffle-oil-100ml',
    name: 'White Truffle Olive Oil 100ml',
    price: 6.38,
    unit: 'per bottle',
    description: 'Premium white truffle infused olive oil',
    category: 'Truffle Oils',
    packaging: '100ml bottle, sold by case',
    available: true,
  },
  {
    id: 'black-truffle-oil-500ml',
    name: 'Black Truffle Olive Oil 500ml',
    price: 21.95,
    unit: 'per tin',
    description: 'Premium black truffle infused olive oil in metal tin',
    category: 'Truffle Oils',
    packaging: '500ml metal tin, sold by case',
    available: true,
  },
  {
    id: 'white-truffle-oil-500ml',
    name: 'White Truffle Olive Oil 500ml',
    price: 23.2,
    unit: 'per tin',
    description: 'Premium white truffle infused olive oil in metal tin',
    category: 'Truffle Oils',
    packaging: '500ml metal tin, sold by case',
    available: true,
  },

  // Salumi
  {
    id: 'black-truffle-salami',
    name: 'Black Truffle Salami',
    price: 7.36,
    unit: 'per 6.5oz',
    description: '100% Berkshire Pork with black truffle. Brown paper wrapped',
    category: 'Salumi',
    packaging: '6.5oz, sold by case',
    available: true,
  },
  {
    id: 'white-truffle-salami',
    name: 'White Truffle Salami',
    price: 7.36,
    unit: 'per 6.5oz',
    description: '100% Berkshire Pork with white truffle. Brown paper wrapped',
    category: 'Salumi',
    packaging: '6.5oz, sold by case',
    available: true,
  },
  {
    id: 'bison-salami',
    name: 'Bison Salami',
    price: 11.63,
    unit: 'per 6.5oz',
    description: '100% Bison. Brown paper wrapped',
    category: 'Salumi',
    packaging: '6.5oz, sold by case',
    available: true,
  },
  {
    id: 'duck-salami',
    name: 'Duck Salami',
    price: 9.25,
    unit: 'per 5.5oz',
    description: '100% Duck meat and duck fat. Brown paper wrapped',
    category: 'Salumi',
    packaging: '5.5oz, sold by case',
    available: true,
  },
  {
    id: 'wild-boar-salami',
    name: 'Wild Boar Salami',
    price: 8.25,
    unit: 'per 5.5oz',
    description: '100% Wild boar meat. Brown paper wrapped',
    category: 'Salumi',
    packaging: '5.5oz, sold by case',
    available: true,
  },

  // Pre-Sliced Salumi
  {
    id: 'pre-sliced-black-truffle-salami',
    name: 'Pre-Sliced Black Truffle Salami',
    price: 5.4,
    unit: 'per 3oz',
    description: 'Ready-to-serve black truffle salami',
    category: 'Pre-Sliced Salumi',
    packaging: '3oz package, sold by case',
    available: true,
  },
  {
    id: 'pre-sliced-duck-breast',
    name: 'Pre-Sliced Dry Cured Duck Breast',
    price: 9.83,
    unit: 'per 2oz',
    description: 'Premium dry cured duck breast, ready to serve',
    category: 'Pre-Sliced Salumi',
    packaging: '2oz package, sold by case',
    available: true,
  },

  // Seasonings
  {
    id: 'black-truffle-salt-50g',
    name: 'Black Summer Truffle Sea Salt 50g',
    price: 8.74,
    unit: 'per jar',
    description: 'Crayssac black truffle infused sea salt',
    category: 'Seasonings',
    packaging: '50g jar, sold by case',
    available: true,
  },
  {
    id: 'white-truffle-salt',
    name: 'White Truffle Himalayan Pink Salt',
    price: 7.0,
    unit: 'per jar',
    description: 'White truffle infused Himalayan pink salt',
    category: 'Seasonings',
    packaging: '80g jar, sold by case',
    available: true,
  },
  {
    id: 'truffle-powder',
    name: 'Black Summer Truffle Powder',
    price: 11.13,
    unit: 'per 50g',
    description: 'Pure black truffle powder for seasoning',
    category: 'Seasonings',
    packaging: '50g package, sold by case',
    available: true,
  },

  // Preserved Products
  {
    id: 'black-truffle-peelings',
    name: 'Black Summer Truffle Peelings',
    price: 29.56,
    unit: 'per jar',
    description: '7oz net drain. Premium preserved truffle peelings',
    category: 'Preserved Products',
    packaging: '7oz jar, sold by case',
    available: true,
  },
  {
    id: 'black-truffle-sauce',
    name: 'Black Truffle Sauce 80g',
    price: 6.45,
    unit: 'per jar',
    description: '5% summer truffle. Ready-to-use truffle sauce',
    category: 'Preserved Products',
    packaging: '80g jar, sold by case',
    available: true,
  },
  {
    id: 'white-truffle-sauce',
    name: 'White Truffle Sauce 80g',
    price: 10.45,
    unit: 'per jar',
    description: '1% Tuber Magnatum Pico. Luxury truffle sauce',
    category: 'Preserved Products',
    packaging: '80g jar, sold by case',
    available: true,
  },

  // Accessories
  {
    id: 'truffle-slicer-rosewood',
    name: 'Italian Rosewood Truffle Slicer',
    price: 35.84,
    unit: 'each',
    description: 'Crayssac Italian rosewood slicer with plain blade and cotton bag',
    category: 'Accessories',
    available: true,
  },
  {
    id: 'truffle-slicer-steel',
    name: 'Stainless Steel Truffle Slicer',
    price: 25.5,
    unit: 'each',
    description: 'Italian stainless steel slicer with plain blade and cotton bag',
    category: 'Accessories',
    available: true,
  },
  {
    id: 'truffle-box',
    name: 'Wooden Truffle Storage Box',
    price: 41.75,
    unit: 'each',
    description: 'Crayssac black matte finish box with red cedar interior',
    category: 'Accessories',
    available: true,
  },
]
